### ISSUE TITLE
Create const for Kind field on ListenConfig and Message structs

### ISSUE THREAD

**Issue by tiagopotencia** [rafaeljesus/rabbus#15]
When i need create a new `ListenConfig` and `Message`, i need to pass a string to `Kind` field. Can we have some const for this? For example, i got an error when pass `"Direct"` not `"direct"` for this field. 

Thanks and congratulations for the great package!

**Comment by rafaeljesus** [comment]
Hi @tiagopotencia glad you liked the library!!

Sure I'll add that that feature 👍 

Nevertheless FYI if you are using rabbus in production check https://github.com/rafaeljesus/rabbus/pull/16 it will be merge tomorrow asap, it fixes some consumer issues while restarting rabbit broker.
